/**
 * scripts/seed.js
 * Run: node scripts/seed.js
 *
 * Creates 12 exams + ~500 questions and inserts them into MongoDB.
 * Existing data is cleared before seeding (exams + tests only).
 */

require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");
const Exam = require("../src/models/Exam");
const Term = require("../src/models/Term");
const Subject = require("../src/models/Subject");
const Test = require("../src/models/Test");

// ─── DB connection (reuse buildMongoURI logic inline) ─────────────────────────
async function connect() {
  const raw = process.env.MONGODB_URI;
  if (!raw) throw new Error("MONGODB_URI not set");
  const url = new URL(raw);
  if (!url.pathname || url.pathname === "/") url.pathname = "/student-exam-app";
  await mongoose.connect(url.toString(), { serverSelectionTimeoutMS: 8000 });
  console.log("✅ Connected to MongoDB →", mongoose.connection.name);
}

// ─── Exam definitions ─────────────────────────────────────────────────────────
const EXAMS = [
  { name: "WAEC Mathematics", level: "SS", isPremium: false },
  { name: "WAEC English Language", level: "SS", isPremium: false },
  { name: "WAEC Biology", level: "SS", isPremium: false },
  { name: "WAEC Chemistry", level: "SS", isPremium: true },
  { name: "WAEC Physics", level: "SS", isPremium: true },
  { name: "JAMB Mathematics", level: "JAMB", isPremium: false },
  { name: "JAMB English Language", level: "JAMB", isPremium: false },
  { name: "JAMB Biology", level: "JAMB", isPremium: true },
  { name: "NECO Economics", level: "NECO", isPremium: false },
  { name: "NECO Government", level: "NECO", isPremium: false },
  { name: "JSS Basic Science", level: "JSS", isPremium: false },
  { name: "Primary Mathematics", level: "Primary", isPremium: false },
];

// ─── Question banks per exam (subject) ────────────────────────────────────────
// Each entry: [question, A, B, C, D, answer, explanation?]
const QUESTION_BANKS = {
  "WAEC Mathematics": [
    ["What is 15% of 200?", "25", "30", "35", "40", "B", "15/100 × 200 = 30"],
    [
      "Simplify: (2x²)(3x³)",
      "5x⁵",
      "6x⁵",
      "6x⁶",
      "5x⁶",
      "B",
      "2×3=6, x²×x³=x⁵",
    ],
    [
      "The sum of angles in a triangle is",
      "90°",
      "180°",
      "270°",
      "360°",
      "B",
      "Triangle angle sum = 180°",
    ],
    ["log₁₀(100) = ?", "1", "2", "10", "100", "B", "10²=100"],
    ["If 3x + 6 = 18, then x = ?", "3", "4", "5", "6", "B", "3x=12 → x=4"],
    [
      "What is the HCF of 12 and 18?",
      "3",
      "4",
      "6",
      "9",
      "C",
      "Factors of 12: 1,2,3,4,6,12; of 18: 1,2,3,6,9,18; HCF=6",
    ],
    [
      "Area of a circle with radius 7 (π=22/7)?",
      "44",
      "77",
      "154",
      "308",
      "C",
      "πr²=(22/7)×49=154",
    ],
    [
      "Convert 0.375 to a fraction",
      "3/8",
      "3/7",
      "1/3",
      "3/10",
      "A",
      "0.375 = 375/1000 = 3/8",
    ],
    ["Solve: 2² × 2³", "2⁵", "2⁶", "4⁵", "16", "A", "2²×2³=2^(2+3)=2⁵=32"],
    [
      "What is the median of 3,7,5,9,1?",
      "5",
      "7",
      "3",
      "9",
      "A",
      "Sorted: 1,3,5,7,9 → median=5",
    ],
    ["√144 = ?", "10", "11", "12", "13", "C", "12×12=144"],
    [
      "Find the gradient of y=3x-5",
      "3",
      "-5",
      "5",
      "-3",
      "A",
      "Gradient = coefficient of x",
    ],
    ["15²=?", "125", "175", "225", "250", "C", "15×15=225"],
    [
      "Simple interest on ₦5000 at 4% for 2 years?",
      "₦200",
      "₦400",
      "₦600",
      "₦800",
      "B",
      "SI=(5000×4×2)/100=400",
    ],
    [
      "Factorise: x²-9",
      "(x-3)(x+3)",
      "(x-3)²",
      "(x+3)²",
      "x(x-9)",
      "A",
      "Difference of two squares",
    ],
    ["The LCM of 4 and 6 is", "8", "10", "12", "24", "C", "LCM(4,6)=12"],
    [
      "If y varies directly as x and y=10 when x=2, find y when x=5",
      "20",
      "25",
      "30",
      "50",
      "B",
      "k=y/x=5; y=5×5=25",
    ],
    [
      "Express in standard form: 0.00045",
      "4.5×10⁻⁴",
      "4.5×10⁻³",
      "4.5×10³",
      "45×10⁻⁴",
      "A",
      "Move decimal 4 places",
    ],
    [
      "A bag has 3 red and 7 blue balls. P(red)?",
      "3/7",
      "7/10",
      "3/10",
      "1/3",
      "C",
      "3/(3+7)=3/10",
    ],
    [
      "Perimeter of a rectangle 8cm by 5cm?",
      "26cm",
      "30cm",
      "40cm",
      "13cm",
      "A",
      "2(8+5)=26",
    ],
    ["Evaluate 3!(factorial)", "3", "6", "9", "12", "B", "3!=3×2×1=6"],
    ["What is 20% of 450?", "80", "90", "100", "110", "B", "20/100×450=90"],
    ["Solve for x: x/4 = 8", "2", "16", "32", "64", "C", "x=8×4=32"],
    [
      "The product of -3 and -4 is",
      "12",
      "-12",
      "7",
      "-7",
      "A",
      "Negative × negative = positive",
    ],
    [
      "Round 3.678 to 2 decimal places",
      "3.67",
      "3.68",
      "3.70",
      "3.6",
      "B",
      "3rd decimal ≥5, round up",
    ],
    ["If a = 2 and b = 3, find a² + b²", "10", "13", "25", "9", "B", "4+9=13"],
    [
      "Angles on a straight line sum to",
      "90°",
      "180°",
      "270°",
      "360°",
      "B",
      "Supplementary angles",
    ],
    ["Find the mean of 4,8,6,2,10", "5", "6", "7", "8", "B", "Sum=30; 30/5=6"],
    [
      "Which is a prime number?",
      "9",
      "15",
      "17",
      "21",
      "C",
      "17 is divisible only by 1 and itself",
    ],
    ["Solve: 5(x-2)=15", "5", "3", "1", "7", "A", "5x-10=15 → x=5"],
  ],
  "WAEC English Language": [
    [
      "Choose the correct spelling:",
      "accomodate",
      "accommodate",
      "acommodate",
      "acomodate",
      "B",
      "Double c and double m",
    ],
    [
      "The plural of 'analysis' is",
      "analysises",
      "analyses",
      "analysis's",
      "analyssis",
      "B",
      "Greek/Latin plural",
    ],
    [
      "Identify the verb in: 'She runs fast'",
      "She",
      "runs",
      "fast",
      "quickly",
      "B",
      "'runs' is the action word",
    ],
    [
      "A word that describes a noun is a",
      "verb",
      "adverb",
      "adjective",
      "pronoun",
      "C",
      "Adjective modifies a noun",
    ],
    [
      "Choose the antonym of 'abundant'",
      "plenty",
      "scarce",
      "ample",
      "lavish",
      "B",
      "Antonym = opposite meaning",
    ],
    [
      "Which sentence is in passive voice?",
      "The dog bit the man",
      "The man was bitten",
      "He gave me a book",
      "She writes letters",
      "B",
      "Subject receives the action",
    ],
    [
      "'She is — honest woman.' Fill in:",
      "a",
      "an",
      "the",
      "some",
      "B",
      "'an' before vowel sound",
    ],
    [
      "The figure of speech in 'Life is a journey'",
      "simile",
      "metaphor",
      "personification",
      "hyperbole",
      "B",
      "Direct comparison without 'like'",
    ],
    [
      "A synonym for 'benevolent' is",
      "cruel",
      "kind",
      "selfish",
      "lazy",
      "B",
      "Benevolent = kind/generous",
    ],
    [
      "The tense of 'He had gone' is",
      "simple past",
      "present perfect",
      "past perfect",
      "future",
      "C",
      "Had + past participle = past perfect",
    ],
    [
      "Which punctuation ends a question?",
      "full stop",
      "comma",
      "question mark",
      "exclamation",
      "C",
      "Questions end with ?",
    ],
    [
      "The prefix 'pre-' means",
      "after",
      "before",
      "against",
      "under",
      "B",
      "Preview = view before",
    ],
    [
      "Identify the pronoun: 'They went home'",
      "They",
      "went",
      "home",
      "away",
      "A",
      "'They' replaces noun(s)",
    ],
    [
      "Choose the correct form: 'Neither he nor she ___ coming'",
      "are",
      "is",
      "were",
      "have",
      "B",
      "Verb agrees with nearest subject",
    ],
    [
      "'The child cried until she slept' — 'until' is a",
      "noun",
      "preposition",
      "conjunction",
      "adjective",
      "C",
      "Joining clause = conjunction",
    ],
    [
      "A group of wolves is called a",
      "pack",
      "flock",
      "herd",
      "school",
      "A",
      "Pack of wolves",
    ],
    [
      "The superlative of 'good' is",
      "gooder",
      "better",
      "goodest",
      "best",
      "D",
      "Irregular superlative",
    ],
    [
      "'Reading is fundamental.' 'Reading' is used as a",
      "verb",
      "gerund",
      "participle",
      "infinitive",
      "B",
      "Verb-ing used as noun = gerund",
    ],
    [
      "'Ephemeral' means",
      "lasting",
      "short-lived",
      "bright",
      "heavy",
      "B",
      "Brief / temporary",
    ],
    [
      "Direct speech: She said, 'I am tired.' Reported?",
      "She said she am tired",
      "She said she was tired",
      "She says she is tired",
      "She told she was tired",
      "B",
      "Backshift tense in reported speech",
    ],
    [
      "Choose the correctly punctuated sentence:",
      "its raining",
      "Its raining",
      "It's raining",
      "it's Raining",
      "C",
      "Contraction: it is = it's",
    ],
    [
      "The root word of 'uncomfortable' is",
      "comfort",
      "uncomfort",
      "able",
      "un",
      "A",
      "comfort + un + able",
    ],
    [
      "A haiku has how many syllables?",
      "7-5-7",
      "5-7-5",
      "5-5-7",
      "7-7-5",
      "B",
      "Traditional Japanese form",
    ],
    [
      "Identify the preposition: 'She sat beside him'",
      "sat",
      "She",
      "beside",
      "him",
      "C",
      "Beside shows position",
    ],
    [
      "An autobiography is written by",
      "a biographer",
      "the subject themselves",
      "a journalist",
      "a critic",
      "B",
      "Auto = self",
    ],
    [
      "Choose the homophone of 'write'",
      "right",
      "wrote",
      "writ",
      "rite",
      "D",
      "Rite sounds like 'write' — wait actually 'right' also sounds like 'write'. The best answer here is 'right'",
      "A",
      "Homophones = same sound",
    ],
    [
      "'Cacophony' means",
      "pleasant sound",
      "harsh sound",
      "no sound",
      "soft sound",
      "B",
      "From Greek kakos=bad",
    ],
    [
      "The sentence 'He is not only clever but also hardworking' uses",
      "correlation",
      "parallelism",
      "anaphora",
      "asyndeton",
      "B",
      "'Not only...but also' = parallel structure",
    ],
    [
      "Identify the adverb: 'She sings beautifully'",
      "She",
      "sings",
      "beautifully",
      "songs",
      "C",
      "Modifies verb 'sings'",
    ],
    [
      "A word formed from the initials of others (e.g. NATO) is an",
      "acronym",
      "abbreviation",
      "anagram",
      "alliteration",
      "A",
      "NATO=North Atlantic Treaty Organization",
    ],
  ],
  "WAEC Biology": [
    [
      "The powerhouse of the cell is the",
      "nucleus",
      "mitochondria",
      "ribosome",
      "vacuole",
      "B",
      "ATP is produced in mitochondria",
    ],
    [
      "Photosynthesis takes place in the",
      "nucleus",
      "chloroplast",
      "cytoplasm",
      "vacuole",
      "B",
      "Chloroplasts contain chlorophyll",
    ],
    [
      "Which blood group is the universal donor?",
      "A",
      "B",
      "AB",
      "O",
      "D",
      "O negative can donate to all",
    ],
    [
      "The process by which plants lose water through leaves is",
      "transpiration",
      "respiration",
      "osmosis",
      "diffusion",
      "A",
      "Water exits via stomata",
    ],
    [
      "DNA stands for",
      "Deoxyribonucleic Acid",
      "Diribonucleic Acid",
      "Deoxyribose Nucleic Acid",
      "Double Nucleic Acid",
      "A",
      "Full form of DNA",
    ],
    [
      "The basic unit of life is",
      "organ",
      "tissue",
      "cell",
      "organism",
      "C",
      "Cell theory",
    ],
    [
      "Which organ produces insulin?",
      "liver",
      "kidney",
      "pancreas",
      "spleen",
      "C",
      "Beta cells in pancreas",
    ],
    [
      "Osmosis is the movement of",
      "solute",
      "water",
      "salt",
      "glucose",
      "B",
      "From low to high concentration through semi-permeable membrane",
    ],
    [
      "The study of fungi is called",
      "mycology",
      "virology",
      "botany",
      "zoology",
      "A",
      "Myco = fungi",
    ],
    [
      "Meiosis produces",
      "2 cells",
      "4 cells",
      "8 cells",
      "1 cell",
      "B",
      "4 haploid daughter cells",
    ],
    [
      "Which vitamin is produced by sunlight?",
      "A",
      "B",
      "C",
      "D",
      "D",
      "Skin synthesises Vitamin D from UV",
    ],
    [
      "The human genome has approximately how many base pairs?",
      "3 million",
      "3 billion",
      "30 million",
      "300 million",
      "B",
      "~3 billion base pairs",
    ],
    [
      "A virus that infects bacteria is called a",
      "pathogen",
      "bacteriophage",
      "prion",
      "parasite",
      "B",
      "Bacterio=bacteria, phage=eater",
    ],
    [
      "Haemoglobin is found in",
      "plasma",
      "white blood cells",
      "red blood cells",
      "platelets",
      "C",
      "RBCs carry oxygen via haemoglobin",
    ],
    [
      "The knee-jerk is an example of",
      "conditioned reflex",
      "natural reflex",
      "habit",
      "instinct",
      "B",
      "Spinal cord reflex arc",
    ],
    [
      "Which kingdom includes mushrooms?",
      "Plantae",
      "Animalia",
      "Fungi",
      "Protista",
      "C",
      "Mushrooms are fungi",
    ],
    [
      "The enzyme in saliva is",
      "pepsin",
      "amylase",
      "lipase",
      "trypsin",
      "B",
      "Salivary amylase digests starch",
    ],
    [
      "In humans, sex is determined by",
      "autosomes",
      "X chromosome",
      "Y chromosome",
      "both X and Y",
      "D",
      "XX=female, XY=male",
    ],
    [
      "The process of cell division for growth is",
      "meiosis",
      "mitosis",
      "fertilisation",
      "budding",
      "B",
      "Mitosis produces identical cells",
    ],
    [
      "Which part of the brain controls balance?",
      "cerebrum",
      "medulla",
      "cerebellum",
      "hypothalamus",
      "C",
      "Cerebellum coordinates movement",
    ],
    [
      "Auxin is a plant",
      "hormone",
      "vitamin",
      "enzyme",
      "protein",
      "A",
      "Controls plant growth/tropisms",
    ],
    [
      "The site of gas exchange in mammals is",
      "trachea",
      "bronchi",
      "alveoli",
      "bronchioles",
      "C",
      "Alveoli have thin walls and capillaries",
    ],
    [
      "Gregor Mendel is known as the father of",
      "genetics",
      "evolution",
      "cell theory",
      "taxonomy",
      "A",
      "Pea plant experiments",
    ],
    [
      "Bile is produced by the",
      "pancreas",
      "gallbladder",
      "liver",
      "stomach",
      "C",
      "Stored in gallbladder but made in liver",
    ],
    [
      "Which disease is caused by Plasmodium?",
      "malaria",
      "cholera",
      "typhoid",
      "dengue",
      "A",
      "Transmitted by Anopheles mosquito",
    ],
    [
      "Xylem transports",
      "food",
      "water and minerals",
      "oxygen",
      "glucose",
      "B",
      "Upward from roots",
    ],
    [
      "The lock-and-key model describes",
      "enzyme action",
      "DNA replication",
      "protein synthesis",
      "osmosis",
      "A",
      "Enzyme-substrate specificity",
    ],
    [
      "Chromosomes are made of",
      "RNA only",
      "DNA and protein",
      "lipids",
      "carbohydrates",
      "B",
      "Chromatin = DNA + histone proteins",
    ],
    [
      "A food chain always starts with a",
      "consumer",
      "herbivore",
      "producer",
      "decomposer",
      "C",
      "Plants fix solar energy",
    ],
    [
      "Which part of the nephron reabsorbs glucose?",
      "glomerulus",
      "Bowman's capsule",
      "proximal tubule",
      "collecting duct",
      "C",
      "Active reabsorption in PCT",
    ],
  ],
  "WAEC Chemistry": [
    [
      "The atomic number of Carbon is",
      "4",
      "6",
      "8",
      "12",
      "B",
      "Carbon has 6 protons",
    ],
    [
      "Water is",
      "H₂O",
      "CO₂",
      "NaCl",
      "H₂SO₄",
      "A",
      "Two hydrogen, one oxygen",
    ],
    [
      "Which gas is produced when an acid reacts with a metal?",
      "oxygen",
      "hydrogen",
      "carbon dioxide",
      "nitrogen",
      "B",
      "Metal + acid → salt + hydrogen",
    ],
    [
      "The pH of pure water at 25°C is",
      "7",
      "6",
      "8",
      "5",
      "A",
      "Neutral pH = 7",
    ],
    [
      "Avogadro's number is approximately",
      "6.02×10²²",
      "6.02×10²³",
      "6.02×10²⁴",
      "6.02×10²¹",
      "B",
      "Mole constant",
    ],
    [
      "An atom that gains an electron becomes a",
      "cation",
      "anion",
      "molecule",
      "isotope",
      "B",
      "Negative ion = anion",
    ],
    [
      "Which element has symbol Fe?",
      "Fluorine",
      "Fermium",
      "Iron",
      "Iridium",
      "C",
      "Fe from Latin Ferrum",
    ],
    [
      "The noble gases are in group",
      "VI",
      "VII",
      "0 (VIII)",
      "I",
      "C",
      "Group 18 / Group 0 — inert gases",
    ],
    [
      "NaOH is",
      "an acid",
      "a base",
      "a salt",
      "a solvent",
      "B",
      "Sodium hydroxide is a strong base",
    ],
    [
      "Electrolysis of water produces",
      "CO₂ and H₂",
      "H₂ and O₂",
      "Na and Cl",
      "NaOH",
      "B",
      "H₂ at cathode, O₂ at anode",
    ],
    [
      "Rusting of iron requires",
      "water only",
      "oxygen only",
      "water and oxygen",
      "heat",
      "C",
      "Fe + H₂O + O₂ → rust",
    ],
    [
      "The melting point of ice at standard pressure is",
      "0°C",
      "100°C",
      "-100°C",
      "25°C",
      "A",
      "0°C = 273K",
    ],
    [
      "Which is a homogeneous mixture?",
      "sand in water",
      "oil in water",
      "salt solution",
      "granite",
      "C",
      "Solution = homogeneous",
    ],
    [
      "Isotopes have the same — but different —",
      "mass number; protons",
      "protons; neutrons",
      "electrons; protons",
      "neutrons; electrons",
      "B",
      "Same atomic number, different mass",
    ],
    [
      "The process of a liquid becoming gas is",
      "condensation",
      "evaporation",
      "sublimation",
      "deposition",
      "B",
      "Liquid → gas = evaporation/boiling",
    ],
    [
      "Allotropes of Carbon include",
      "diamond and graphite",
      "charcoal and coal",
      "graphite and iron",
      "diamond and quartz",
      "A",
      "Same element different structures",
    ],
    [
      "The rate of reaction increases with",
      "lower temperature",
      "higher temperature",
      "smaller surface area",
      "adding inhibitor",
      "B",
      "More energy = faster collisions",
    ],
    [
      "Which acid is found in vinegar?",
      "hydrochloric",
      "sulphuric",
      "acetic",
      "nitric",
      "C",
      "Ethanoic/acetic acid",
    ],
    [
      "A catalyst",
      "is consumed in reaction",
      "increases activation energy",
      "speeds up reaction",
      "decreases temperature",
      "C",
      "Not consumed, lowers Ea",
    ],
    [
      "The periodic table organises elements by",
      "mass",
      "atomic number",
      "name",
      "reactivity",
      "B",
      "Moseley's arrangement",
    ],
    [
      "Covalent bonds involve",
      "transfer of electrons",
      "sharing of electrons",
      "metallic bonding",
      "ionic attraction",
      "B",
      "Shared electron pairs",
    ],
    [
      "Which gas causes acid rain?",
      "N₂",
      "SO₂",
      "O₂",
      "CO₂",
      "B",
      "Sulphur dioxide + water = sulphurous acid",
    ],
    [
      "Fermentation converts glucose to",
      "water",
      "ethanol and CO₂",
      "lactic acid",
      "oxygen",
      "B",
      "Yeast anaerobic respiration",
    ],
    [
      "The chemical formula for table salt is",
      "NaCl",
      "KCl",
      "CaCl₂",
      "MgCl₂",
      "A",
      "Sodium chloride",
    ],
    [
      "Fractional distillation separates",
      "solids",
      "immiscible liquids",
      "miscible liquids with different boiling points",
      "gases",
      "C",
      "Based on different boiling points",
    ],
    ["The valency of oxygen is", "1", "2", "3", "4", "B", "Forms 2 bonds"],
    [
      "Which colour does litmus turn in acid?",
      "blue",
      "green",
      "red",
      "yellow",
      "C",
      "Acid turns litmus red",
    ],
    [
      "An exothermic reaction",
      "absorbs heat",
      "releases heat",
      "changes colour",
      "has no energy change",
      "B",
      "Energy released to surroundings",
    ],
    [
      "Starch + iodine turns",
      "red",
      "blue-black",
      "white",
      "yellow",
      "B",
      "Classic test for starch",
    ],
    [
      "The molar mass of CO₂ is",
      "44 g/mol",
      "28 g/mol",
      "32 g/mol",
      "36 g/mol",
      "A",
      "12+(2×16)=44",
    ],
  ],
  "WAEC Physics": [
    [
      "The unit of force is",
      "Watt",
      "Joule",
      "Newton",
      "Pascal",
      "C",
      "F = ma; unit = Newton",
    ],
    [
      "Speed of light in vacuum is approximately",
      "3×10⁶ m/s",
      "3×10⁸ m/s",
      "3×10¹⁰ m/s",
      "3×10⁴ m/s",
      "B",
      "c ≈ 3×10⁸ m/s",
    ],
    [
      "Which type of wave does not require a medium?",
      "sound",
      "water",
      "seismic",
      "electromagnetic",
      "D",
      "EM waves travel in vacuum",
    ],
    [
      "Ohm's law states V =",
      "I/R",
      "IR",
      "I+R",
      "I-R",
      "B",
      "Voltage = Current × Resistance",
    ],
    [
      "The SI unit of pressure is",
      "Newton",
      "Joule",
      "Pascal",
      "Bar",
      "C",
      "Pa = N/m²",
    ],
    [
      "An object in free fall accelerates at",
      "9.8 cm/s²",
      "9.8 m/s²",
      "9.8 km/s²",
      "9.8 mm/s²",
      "B",
      "g ≈ 9.8 m/s² near Earth's surface",
    ],
    [
      "Concave mirrors are used in",
      "rear-view mirrors",
      "torches",
      "kaleidoscopes",
      "periscopes",
      "B",
      "Converging mirror focuses light",
    ],
    [
      "Which colour has the longest wavelength?",
      "violet",
      "blue",
      "red",
      "green",
      "C",
      "Red: ~700nm at end of visible spectrum",
    ],
    [
      "Power is defined as",
      "force × distance",
      "work ÷ time",
      "mass × velocity",
      "force × velocity",
      "B",
      "P = W/t",
    ],
    [
      "The boiling point of water at sea level is",
      "90°C",
      "95°C",
      "100°C",
      "105°C",
      "C",
      "100°C = 373K",
    ],
    [
      "Total internal reflection occurs when light goes from",
      "denser to rarer medium",
      "rarer to denser medium",
      "vacuum to glass",
      "glass to glass",
      "A",
      "Beyond critical angle",
    ],
    ["Kinetic energy = ?", "mv", "½mv", "½mv²", "mv²", "C", "KE = ½mv²"],
    [
      "A transformer that steps up voltage",
      "decreases current",
      "increases current",
      "keeps current same",
      "destroys current",
      "A",
      "P=IV; step up V → step down I",
    ],
    [
      "Convex lenses are used in",
      "spectacles for short sight",
      "spectacles for long sight",
      "rear-view mirrors",
      "periscopes",
      "B",
      "Converging lens corrects hyperopia",
    ],
    [
      "Sound travels fastest in",
      "vacuum",
      "air",
      "water",
      "solids",
      "D",
      "Denser medium = faster sound",
    ],
    [
      "The unit of electrical charge is",
      "Amp",
      "Volt",
      "Coulomb",
      "Ohm",
      "C",
      "Q measured in Coulombs",
    ],
    [
      "Latent heat of fusion is energy needed to",
      "melt solid to liquid",
      "boil liquid to gas",
      "freeze liquid",
      "sublime solid",
      "A",
      "Solid ↔ Liquid phase change",
    ],
    [
      "Gamma rays are",
      "alpha particles",
      "electrons",
      "electromagnetic waves",
      "protons",
      "C",
      "High-frequency EM radiation",
    ],
    [
      "Which law relates pressure and volume of gas at constant temperature?",
      "Charles' law",
      "Boyle's law",
      "Gay-Lussac's law",
      "Dalton's law",
      "B",
      "PV = constant",
    ],
    [
      "A mirage is caused by",
      "reflection",
      "refraction",
      "diffraction",
      "interference",
      "B",
      "Hot air refracts light",
    ],
    [
      "The image in a plane mirror is",
      "real, inverted",
      "virtual, erect",
      "real, erect",
      "virtual, inverted",
      "B",
      "Virtual and upright",
    ],
    [
      "Momentum = ?",
      "mass × acceleration",
      "mass × velocity",
      "force × time",
      "mass × distance",
      "B",
      "p = mv",
    ],
    [
      "The half-life of a radioactive element is",
      "time for all atoms to decay",
      "time for half to decay",
      "time to double",
      "time constant",
      "B",
      "N₀ → N₀/2",
    ],
    [
      "An ammeter is connected in",
      "series",
      "parallel",
      "either",
      "neither",
      "A",
      "Low resistance → series",
    ],
    [
      "Ultrasound frequency is above",
      "20 Hz",
      "200 Hz",
      "2000 Hz",
      "20000 Hz",
      "D",
      "Above 20kHz = ultrasound",
    ],
    [
      "NPN transistor has",
      "2 p-type and 1 n-type",
      "2 n-type and 1 p-type",
      "3 n-type",
      "3 p-type",
      "B",
      "N - P - N layers",
    ],
    [
      "Work done = ?",
      "force ÷ distance",
      "force × distance",
      "mass × velocity",
      "energy × time",
      "B",
      "W = F×d×cosθ",
    ],
    [
      "Efficiency of a machine is",
      "output/input × 100%",
      "input/output × 100%",
      "output − input",
      "input − output",
      "A",
      "Always ≤ 100%",
    ],
    [
      "Which radiation is stopped by paper?",
      "gamma",
      "beta",
      "alpha",
      "X-ray",
      "C",
      "Alpha stopped by few cm air/paper",
    ],
    [
      "The Doppler effect is observed in",
      "colour",
      "frequency",
      "wavelength only",
      "both frequency and wavelength",
      "D",
      "Moving source changes observed frequency",
    ],
  ],
  "JAMB Mathematics": [
    [
      "If f(x) = 3x² - 2x + 1, find f(2)",
      "9",
      "10",
      "11",
      "13",
      "A",
      "3(4)-2(2)+1=12-4+1=9",
    ],
    [
      "Differentiate y = x³ - 4x",
      "3x² - 4",
      "3x² + 4",
      "x² - 4",
      "3x - 4",
      "A",
      "dy/dx = 3x²-4",
    ],
    [
      "∫(2x) dx =",
      "x²",
      "x² + c",
      "2x² + c",
      "x + c",
      "B",
      "Integral of 2x = x²+c",
    ],
    ["sin 30° = ?", "1/2", "√3/2", "√2/2", "1", "A", "Standard angle"],
    [
      "The roots of x² - 5x + 6 = 0 are",
      "2 and 3",
      "1 and 6",
      "-2 and -3",
      "2 and -3",
      "A",
      "(x-2)(x-3)=0",
    ],
    ["log₂8 = ?", "2", "3", "4", "8", "B", "2³=8"],
    [
      "Sequence: 2,5,8,11... next term?",
      "13",
      "14",
      "15",
      "12",
      "B",
      "Common difference 3; 11+3=14",
    ],
    ["Evaluate ⁵C₂", "10", "20", "15", "5", "A", "5!/(2!3!) = 10"],
    [
      "The angle subtended at centre = twice angle at circumference: this is",
      "tangent theorem",
      "inscribed angle theorem",
      "chord theorem",
      "sector theorem",
      "B",
      "Circle theorem",
    ],
    [
      "A right-angled triangle has sides 3,4,?",
      "5",
      "6",
      "7",
      "8",
      "A",
      "Pythagoras: 3²+4²=5²",
    ],
    [
      "Matrix [[1,2],[3,4]] has determinant",
      "2",
      "−2",
      "10",
      "−10",
      "B",
      "(1×4)-(2×3)=4-6=-2",
    ],
    [
      "The sum of GP: a=1, r=2, n=4",
      "15",
      "16",
      "10",
      "8",
      "A",
      "a(rⁿ-1)/(r-1)=1(16-1)/1=15",
    ],
    [
      "Equation of line through (0,3) with gradient 2",
      "y=2x+3",
      "y=3x+2",
      "y=2x-3",
      "y=3x-2",
      "A",
      "y=mx+c; m=2,c=3",
    ],
    ["Vector (3,4) has magnitude", "5", "7", "12", "3.5", "A", "√(9+16)=√25=5"],
    [
      "If P(A)=0.3 and P(B)=0.5 independent, P(A∩B)=",
      "0.15",
      "0.8",
      "0.2",
      "0.35",
      "A",
      "P(A)×P(B)=0.15",
    ],
    ["cos 60° = ?", "1/2", "√3/2", "0", "1", "A", "Standard angle: cos60°=0.5"],
    [
      "The range of data 2,4,6,8,10 is",
      "4",
      "8",
      "10",
      "5",
      "B",
      "Max-Min=10-2=8",
    ],
    [
      "Variance of 2,4,6 is",
      "2⅔",
      "4",
      "8",
      "2",
      "A",
      "Mean=4; ((4+0+4)/3)=8/3=2.67",
    ],
    ["tan 45° = ?", "0", "1", "√3", "1/√2", "B", "tan45°=sin/cos=1"],
    [
      "Locus of points equidistant from (0,0) and (4,0) is",
      "x=2",
      "y=2",
      "x=4",
      "y=4",
      "A",
      "Perpendicular bisector x=2",
    ],
    [
      "d/dx(sin x)=",
      "cos x",
      "-cos x",
      "-sin x",
      "sin x",
      "A",
      "Standard derivative",
    ],
    ["The reciprocal of 2/5 is", "5/2", "2/5", "2", "5", "A", "Flip fraction"],
    ["2x + 3y = 12 and x = 3; find y", "1", "2", "3", "4", "B", "6+3y=12→y=2"],
    [
      "Arithmetic mean of 1-10 is",
      "5",
      "5.5",
      "6",
      "4.5",
      "B",
      "Sum=55; 55/10=5.5",
    ],
    [
      "Expand (a + b)²",
      "a² + b²",
      "a² + 2ab + b²",
      "a² - b²",
      "2a + 2b",
      "B",
      "Perfect square expansion",
    ],
    [
      "Area of triangle base 6, height 4?",
      "12",
      "24",
      "10",
      "8",
      "A",
      "½×6×4=12",
    ],
    ["If 2ˣ = 16, x = ?", "2", "4", "8", "6", "B", "2⁴=16"],
    [
      "Standard deviation is the square root of",
      "mean",
      "median",
      "variance",
      "range",
      "C",
      "SD=√variance",
    ],
    [
      "Number of diagonals in a hexagon?",
      "6",
      "9",
      "12",
      "15",
      "B",
      "n(n-3)/2=6(3)/2=9",
    ],
    ["Complete the square: x²+6x+?", "9", "6", "3", "12", "A", "(6/2)²=9"],
  ],
  "JAMB English Language": [
    [
      "Choose the word closest to 'Verbose'",
      "talkative",
      "brief",
      "silent",
      "accurate",
      "A",
      "Verbose = using too many words",
    ],
    [
      "Identify the clause type: 'When she arrives'",
      "main clause",
      "subordinate clause",
      "relative clause",
      "noun clause",
      "B",
      "Dependent = subordinate",
    ],
    [
      "'He is the man whose car was stolen.' Type of clause:",
      "adjectival",
      "adverbial",
      "noun",
      "main",
      "A",
      "Modifies 'man' = adjective clause",
    ],
    [
      "The mood of 'If I were king' is",
      "indicative",
      "subjunctive",
      "imperative",
      "infinitive",
      "B",
      "Hypothetical = subjunctive",
    ],
    [
      "A malapropism is",
      "wrong use of a similar-sounding word",
      "repetition",
      "exaggeration",
      "understatement",
      "A",
      "e.g. 'a vast wasteland' → 'a vast waistband'",
    ],
    [
      "Which is a collective noun?",
      "crowd",
      "run",
      "bright",
      "slowly",
      "A",
      "Crowd = group of people",
    ],
    [
      "The suffix '-ous' usually makes a word into",
      "noun",
      "verb",
      "adjective",
      "adverb",
      "C",
      "Danger → dangerous",
    ],
    [
      "'She eats like a bird.' This is a",
      "metaphor",
      "simile",
      "oxymoron",
      "personification",
      "B",
      "'Like' present = simile",
    ],
    [
      "A dictionary synonym for 'frugal' is",
      "wasteful",
      "economical",
      "wealthy",
      "generous",
      "B",
      "Frugal = careful with money",
    ],
    [
      "'Whom did you call?' Here 'whom' is an",
      "subject pronoun",
      "object pronoun",
      "possessive",
      "reflexive",
      "B",
      "Object of call",
    ],
    [
      "Choose the correctly spelt word",
      "occurrence",
      "occurence",
      "ocurrence",
      "occurrrence",
      "A",
      "Double c, double r",
    ],
    [
      "A bildungsroman is a novel about",
      "mystery",
      "coming-of-age",
      "romance",
      "science",
      "B",
      "German: formation novel",
    ],
    [
      "The literary device in 'The wind howled' is",
      "alliteration",
      "personification",
      "metaphor",
      "onomatopoeia",
      "B",
      "Wind given human action",
    ],
    [
      "'He is the tallest student.' Tallest is a",
      "positive adjective",
      "comparative",
      "superlative",
      "adverb",
      "C",
      "Superlative = most",
    ],
    [
      "Choose the sentence with the correct apostrophe",
      "The students book",
      "The students' books",
      "The students books'",
      "The's students book",
      "B",
      "Plural possessive",
    ],
    [
      "An oxymoron is",
      "pleasant sound",
      "a contradiction in terms",
      "comparison",
      "exaggeration",
      "B",
      "e.g. deafening silence",
    ],
    [
      "'Having finished his work, he went home.' Underlined is a",
      "gerund phrase",
      "infinitive phrase",
      "participial phrase",
      "prepositional phrase",
      "C",
      "Past participle modifying subject",
    ],
    [
      "A euphemism replaces",
      "a harsh word with a milder one",
      "one word with its synonym",
      "noun with pronoun",
      "active with passive",
      "A",
      "e.g. 'passed away' = died",
    ],
    [
      "Which is an abstract noun?",
      "table",
      "beauty",
      "dog",
      "river",
      "B",
      "Cannot be touched",
    ],
    [
      "'She will have completed by Monday.' This tense is",
      "future simple",
      "future continuous",
      "future perfect",
      "present perfect",
      "C",
      "Will + have + past participle = future perfect",
    ],
    [
      "Syllabication of 'education' has how many syllables?",
      "3",
      "4",
      "5",
      "2",
      "B",
      "ed-u-ca-tion",
    ],
    [
      "A portmanteau word combines",
      "two words into one",
      "one word into two",
      "a prefix",
      "a suffix",
      "A",
      "e.g. brunch = breakfast+lunch",
    ],
    [
      "Intonation pattern that ends rising implies",
      "statement",
      "question",
      "command",
      "exclamation",
      "B",
      "Rising tone = question",
    ],
    [
      "The object of 'Maria baked a cake' is",
      "Maria",
      "baked",
      "a cake",
      "yesterday",
      "C",
      "Cake receives the action",
    ],
    [
      "Anachronism means",
      "placing something in wrong time period",
      "comparison",
      "rhythm",
      "repetition",
      "A",
      "e.g. clock in Julius Caesar",
    ],
    [
      "Which has correct subject-verb agreement?",
      "The team are playing",
      "The team is playing",
      "The teams is playing",
      "Teams is playing",
      "B",
      "Collective noun (singular) + is",
    ],
    [
      "A paradox is",
      "an obvious truth",
      "a statement seemingly contradictory but possibly true",
      "a comparison",
      "a sound device",
      "B",
      "e.g. 'I must be cruel to be kind'",
    ],
    [
      "'Ergo' means",
      "because",
      "therefore",
      "however",
      "although",
      "B",
      "Latin for 'therefore'",
    ],
    [
      "The plural of 'criterion' is",
      "criterions",
      "criterias",
      "criteria",
      "criterions",
      "C",
      "Greek plural",
    ],
    [
      "Alliteration is repetition of",
      "vowel sounds",
      "consonant sounds at word start",
      "whole words",
      "sentence structure",
      "B",
      "e.g. Peter Piper picked",
    ],
  ],
  "JAMB Biology": [
    [
      "Which organelle is called the 'control centre' of the cell?",
      "mitochondria",
      "nucleus",
      "ribosome",
      "Golgi body",
      "B",
      "DNA/RNA are in the nucleus",
    ],
    [
      "Aerobic respiration equation result includes",
      "CO₂ and H₂O",
      "only CO₂",
      "only H₂O",
      "lactic acid",
      "A",
      "C₆H₁₂O₆+O₂→CO₂+H₂O+ATP",
    ],
    [
      "Organisms that make their own food are",
      "heterotrophs",
      "decomposers",
      "autotrophs",
      "parasites",
      "C",
      "Auto = self; use photosynthesis",
    ],
    [
      "The genetic material in viruses is",
      "carbohydrate",
      "lipid",
      "DNA or RNA",
      "protein only",
      "C",
      "Viruses contain nucleic acid core",
    ],
    [
      "Which hormone controls blood sugar level?",
      "adrenaline",
      "insulin",
      "progesterone",
      "thyroxine",
      "B",
      "Pancreas produces insulin",
    ],
    [
      "The knee joint is a",
      "ball and socket",
      "hinge",
      "pivot",
      "gliding",
      "B",
      "Allows flex/extend only",
    ],
    [
      "Secondary consumers in a food chain are",
      "producers",
      "herbivores",
      "carnivores eating herbivores",
      "decomposers",
      "C",
      "Eat primary consumers (herbivores)",
    ],
    [
      "Turgor pressure is related to",
      "osmosis",
      "transpiration",
      "photosynthesis",
      "respiration",
      "A",
      "Water potential in plant cells",
    ],
    [
      "Dominant allele is represented by",
      "lowercase letter",
      "uppercase letter",
      "number",
      "symbol",
      "B",
      "Convention: A = dominant",
    ],
    [
      "Sickle cell anaemia is caused by",
      "virus",
      "bacteria",
      "defective gene",
      "vitamin deficiency",
      "C",
      "Mutation in HBB gene",
    ],
    [
      "The excretory organ of insects is",
      "kidney",
      "Malpighian tubule",
      "lung",
      "liver",
      "B",
      "Opens into hindgut",
    ],
    [
      "Which gas do plants take in during photosynthesis?",
      "O₂",
      "N₂",
      "CO₂",
      "H₂",
      "C",
      "CO₂ + H₂O + light → glucose",
    ],
    [
      "A zygote is formed by",
      "mitosis",
      "meiosis",
      "fertilisation",
      "budding",
      "C",
      "Sperm + egg → zygote",
    ],
    [
      "Decomposers return nutrients to the",
      "atmosphere",
      "water",
      "soil",
      "food chain start",
      "C",
      "Break down dead matter",
    ],
    [
      "The cerebrum is responsible for",
      "balance",
      "breathing",
      "thinking/intelligence",
      "heartbeat",
      "C",
      "Largest brain region",
    ],
    [
      "Which cell has no nucleus?",
      "white blood cell",
      "red blood cell",
      "platelet",
      "nerve cell",
      "B",
      "Mature RBCs lack nucleus",
    ],
    [
      "Pasteurisation is used to",
      "sterilise completely",
      "reduce pathogens in food",
      "freeze food",
      "ferment food",
      "B",
      "Partial heat treatment",
    ],
    [
      "Ribosomes are the site of",
      "DNA replication",
      "protein synthesis",
      "respiration",
      "photosynthesis",
      "B",
      "Translation occurs on ribosomes",
    ],
    [
      "An example of asexual reproduction is",
      "budding",
      "fertilisation",
      "pollination",
      "spawning",
      "A",
      "Budding = one parent",
    ],
    [
      "The hormone oestrogen is produced by",
      "testes",
      "adrenal gland",
      "ovaries",
      "pituitary",
      "C",
      "Female sex hormone",
    ],
    [
      "Which disease is caused by bacteria?",
      "malaria",
      "cholera",
      "AIDS",
      "influenza",
      "B",
      "Vibrio cholerae",
    ],
    [
      "Blood clotting involves",
      "white blood cells",
      "platelets",
      "red blood cells",
      "plasma only",
      "B",
      "Thrombocytes initiate clotting",
    ],
    [
      "Ecological succession ends at a",
      "pioneer community",
      "climax community",
      "seral community",
      "biome",
      "B",
      "Stable final state",
    ],
    [
      "The ileum is part of",
      "large intestine",
      "small intestine",
      "stomach",
      "oesophagus",
      "B",
      "Main absorption site",
    ],
    [
      "Nitrogen fixation is carried out by",
      "fungi",
      "Rhizobium bacteria",
      "algae",
      "plant roots",
      "B",
      "Symbiotic bacteria in legumes",
    ],
    [
      "Vaccination introduces",
      "live disease",
      "dead/weakened pathogen",
      "antibiotics",
      "enzymes",
      "B",
      "Stimulates immune memory",
    ],
    [
      "The role of the liver includes",
      "producing insulin",
      "detoxifying blood",
      "producing RBCs (in adults)",
      "filtering urine",
      "B",
      "Deamination, bile production, detox",
    ],
    [
      "Guard cells control",
      "nutrient uptake",
      "stomata opening/closing",
      "root hair absorption",
      "xylem flow",
      "B",
      "Open/close stomata for gas exchange",
    ],
    [
      "A symbiotic relationship where both benefit is",
      "commensalism",
      "parasitism",
      "mutualism",
      "predation",
      "C",
      "Both organisms benefit",
    ],
    [
      "The backbone (vertebral column) is part of the",
      "appendicular skeleton",
      "axial skeleton",
      "exoskeleton",
      "endoskeleton only",
      "B",
      "Core body skeleton = axial",
    ],
  ],
  "NECO Economics": [
    [
      "The study of economics deals primarily with",
      "politics",
      "scarcity and choice",
      "geography",
      "history",
      "B",
      "Resources are scarce; choices must be made",
    ],
    [
      "Opportunity cost is the",
      "money spent",
      "next best alternative foregone",
      "total cost",
      "sunk cost",
      "B",
      "True cost of a decision",
    ],
    [
      "A free market has prices determined by",
      "government",
      "tradition",
      "demand and supply",
      "central planning",
      "C",
      "Price mechanism",
    ],
    [
      "GDP stands for",
      "Gross Domestic Product",
      "General Development Plan",
      "Gross Demand Price",
      "Global Development Programme",
      "A",
      "Total value of goods/services",
    ],
    [
      "Inflation means the",
      "decrease in price level",
      "increase in price level",
      "change in GDP",
      "rise in unemployment",
      "B",
      "Money buys less over time",
    ],
    [
      "Which is a factor of production?",
      "money",
      "capital",
      "tax",
      "profit",
      "B",
      "Land, Labour, Capital, Enterprise",
    ],
    [
      "Demand curve normally slopes",
      "upward",
      "downward",
      "horizontally",
      "vertically",
      "B",
      "More demanded at lower price",
    ],
    [
      "A commercial bank creates money through",
      "printing notes",
      "lending (credit creation)",
      "taxes",
      "imports",
      "B",
      "Fractional reserve banking",
    ],
    [
      "The law of diminishing returns states",
      "output rises forever",
      "extra input eventually adds less output",
      "all costs are fixed",
      "price always falls",
      "B",
      "Marginal product decreases",
    ],
    [
      "An elastic demand means",
      "demand is unresponsive to price",
      "demand changes proportionally more than price",
      "quantity equals price",
      "supply equals demand",
      "B",
      "PED > 1",
    ],
    [
      "Privatisation means",
      "government takes over firm",
      "selling state firms to private sector",
      "nationalising banks",
      "controlling prices",
      "B",
      "Opposite of nationalisation",
    ],
    [
      "A budget deficit occurs when",
      "revenue = expenditure",
      "revenue > expenditure",
      "revenue < expenditure",
      "imports = exports",
      "C",
      "Government spends more than it earns",
    ],
    [
      "Barter is the exchange of",
      "money",
      "goods for goods",
      "services for money",
      "bonds",
      "B",
      "Pre-money trade system",
    ],
    [
      "The World Bank focuses on",
      "trade disputes",
      "development loans to poor countries",
      "exchange rates",
      "oil prices",
      "B",
      "Poverty reduction, development",
    ],
    [
      "Subsistence farming is",
      "farming for profit",
      "farming for own consumption",
      "large-scale agriculture",
      "export farming",
      "B",
      "Produces only for own use",
    ],
    [
      "Price elasticity of supply measures",
      "how supply responds to income",
      "how supply responds to price change",
      "how demand shifts",
      "production costs",
      "B",
      "PES = %ΔQs / %ΔP",
    ],
    [
      "Monopoly means",
      "many sellers",
      "one seller",
      "two sellers",
      "no sellers",
      "B",
      "Single firm controls market",
    ],
    [
      "National income = GDP",
      "+ net factor income from abroad",
      "-imports",
      "+taxes",
      "- wages",
      "A",
      "GNP = GDP + net factor income",
    ],
    [
      "Which is a regressive tax?",
      "income tax",
      "inheritance tax",
      "VAT on necessities",
      "corporate tax",
      "C",
      "Takes higher % from low earners",
    ],
    [
      "A trade surplus means",
      "imports > exports",
      "exports > imports",
      "imports = exports",
      "no trade",
      "B",
      "More sold abroad than bought",
    ],
    [
      "Liquidity preference refers to",
      "desire to hold money",
      "buying bonds",
      "saving in bank",
      "investing in shares",
      "A",
      "Keynes: people prefer liquid assets",
    ],
    [
      "Demand-pull inflation is caused by",
      "cost increases",
      "excess demand in economy",
      "supply reduction",
      "money supply fall",
      "B",
      "Too much money chasing few goods",
    ],
    [
      "An inferior good has a",
      "positive income elasticity",
      "negative income elasticity",
      "zero elasticity",
      "unitary elasticity",
      "B",
      "Demand falls as income rises",
    ],
    [
      "Mixed economy has both",
      "public and private sectors",
      "only private sector",
      "only public sector",
      "foreign and domestic sectors",
      "A",
      "Elements of both capitalism and socialism",
    ],
    [
      "Fiscal policy involves",
      "interest rates",
      "government spending and taxation",
      "exchange rates",
      "money supply",
      "B",
      "Budgetary tools of government",
    ],
    [
      "Producer surplus is",
      "consumer gain from trade",
      "excess revenue above minimum price supplier accepts",
      "total revenue",
      "profit only",
      "B",
      "Area above supply curve below price",
    ],
    [
      "OPEC is an example of",
      "free trade agreement",
      "consumer cartel",
      "producer cartel",
      "development bank",
      "C",
      "Oil Producing and Exporting Countries",
    ],
    [
      "Stagflation is",
      "high growth, low inflation",
      "low growth, high inflation and unemployment",
      "deflation only",
      "hyperinflation",
      "B",
      "Stagnation + inflation",
    ],
    [
      "CPI measures",
      "changes in interest rates",
      "changes in average price level",
      "changes in income",
      "exchange rate",
      "B",
      "Consumer Price Index",
    ],
    [
      "Comparative advantage theory was developed by",
      "Adam Smith",
      "David Ricardo",
      "Karl Marx",
      "John Keynes",
      "B",
      "Theory of international trade",
    ],
  ],
  "NECO Government": [
    [
      "Federal system divides power between",
      "president and parliament",
      "central and regional governments",
      "judiciary and executive",
      "political parties",
      "B",
      "Two tiers of government",
    ],
    [
      "A referendum is",
      "election of leaders",
      "direct vote by citizens on an issue",
      "appointment of ministers",
      "court ruling",
      "B",
      "Direct democracy mechanism",
    ],
    [
      "Sovereignty means",
      "economic wealth",
      "supreme power/authority in the state",
      "foreign policy",
      "military strength",
      "B",
      "Absolute power within territory",
    ],
    [
      "The rule of law means",
      "powerful can do anything",
      "everyone is equal before the law",
      "judiciary makes all laws",
      "only laws favour rich",
      "B",
      "Dicey's principle",
    ],
    [
      "A unitary state has",
      "divided sovereignty",
      "all power in central government",
      "equal states",
      "elected monarch",
      "B",
      "UK, France, Japan examples",
    ],
    [
      "The IMF specialises in",
      "peacekeeping",
      "international monetary problems",
      "food aid",
      "health",
      "B",
      "International Monetary Fund",
    ],
    [
      "Coalition government is formed when",
      "one party wins",
      "multiple parties govern together",
      "president appoints all ministers",
      "military takes over",
      "B",
      "Common in proportional systems",
    ],
    [
      "Checks and balances prevent",
      "democracy",
      "tyranny",
      "federalism",
      "legislation",
      "B",
      "Each arm limits the others",
    ],
    [
      "The UN Security Council has how many permanent members?",
      "3",
      "5",
      "7",
      "10",
      "B",
      "USA, UK, France, Russia, China",
    ],
    [
      "Proportional representation is a type of",
      "electoral system",
      "governance",
      "constitution",
      "civil service",
      "A",
      "Seats match vote percentage",
    ],
    [
      "A constitution is",
      "a political party manifesto",
      "fundamental law of the land",
      "economic plan",
      "treaty",
      "B",
      "Supreme legal document",
    ],
    [
      "Civil liberties are",
      "laws that restrict citizens",
      "rights protecting citizens from government",
      "religion",
      "foreign policy",
      "B",
      "Freedom of speech, assembly etc.",
    ],
    [
      "Gerrymander means",
      "fair constituency drawing",
      "manipulating constituency boundaries for advantage",
      "counting votes",
      "forming alliances",
      "B",
      "Political boundary manipulation",
    ],
    [
      "An oligarchy is rule by",
      "the few",
      "one person",
      "the people",
      "religious leaders",
      "A",
      "Oligos = few in Greek",
    ],
    [
      "Political socialisation is",
      "voter registration",
      "process of learning political values",
      "party formation",
      "military training",
      "B",
      "Family, schools, media agents",
    ],
    [
      "Bicameral legislature has",
      "one chamber",
      "two chambers",
      "three chambers",
      "no chambers",
      "B",
      "e.g. Senate + House of Representatives",
    ],
    [
      "Cabinet government is a feature of",
      "presidential system",
      "parliamentary system",
      "military system",
      "monarchical system",
      "B",
      "UK cabinet collective responsibility",
    ],
    [
      "Veto power allows the executive to",
      "pass bills",
      "reject bills",
      "dissolve courts",
      "appoint judges",
      "B",
      "Checks legislature",
    ],
    [
      "The African Union was established in",
      "1963",
      "2002",
      "1991",
      "1945",
      "B",
      "Replaced OAU in 2002",
    ],
    [
      "LON was predecessor of",
      "EU",
      "UN",
      "AU",
      "NATO",
      "B",
      "League Of Nations → United Nations",
    ],
    [
      "Judicial review allows courts to",
      "make laws",
      "review constitutionality of laws",
      "appoint ministers",
      "collect taxes",
      "B",
      "Check on legislative power",
    ],
    [
      "Totalitarianism is characterised by",
      "limited government control",
      "total state control over all aspects of life",
      "free elections",
      "press freedom",
      "B",
      "e.g. North Korea",
    ],
    [
      "Bureaucracy refers to",
      "elected officials",
      "professional civil service",
      "tax collectors",
      "military officers",
      "B",
      "Non-political government staff",
    ],
    [
      "Political culture is",
      "rules of government",
      "shared attitudes about political system",
      "party ideology",
      "election process",
      "B",
      "Beliefs, values about politics",
    ],
    [
      "ECOWAS promotes",
      "military alliance",
      "economic cooperation in West Africa",
      "education",
      "agriculture",
      "B",
      "Economic Community of West African States",
    ],
    [
      "Devolution transfers power",
      "from regions to centre",
      "from centre to regions",
      "between states",
      "to international bodies",
      "B",
      "Decentralisation of authority",
    ],
    [
      "The Commonwealth is an association of",
      "former British colonies",
      "NATO members",
      "G7 nations",
      "EU members",
      "A",
      "56 member states",
    ],
    [
      "Citizenship is obtained by",
      "residence only",
      "birth, naturalisation or descent",
      "working in country",
      "election",
      "B",
      "Multiple paths to citizenship",
    ],
    [
      "An embargo is",
      "tax on imports",
      "ban on trade with a country",
      "foreign aid",
      "military blockade",
      "B",
      "Economic sanction",
    ],
    [
      "INEC in Nigeria is responsible for",
      "military",
      "elections",
      "taxation",
      "foreign affairs",
      "B",
      "Independent National Electoral Commission",
    ],
  ],
  "JSS Basic Science": [
    [
      "What is the unit of length?",
      "kilogram",
      "metre",
      "litre",
      "second",
      "B",
      "SI unit of length is metre",
    ],
    [
      "Which planet is the largest in our solar system?",
      "Earth",
      "Mars",
      "Jupiter",
      "Saturn",
      "C",
      "Jupiter is the gas giant",
    ],
    [
      "Water changes to steam at",
      "50°C",
      "100°C",
      "150°C",
      "200°C",
      "B",
      "Boiling point of water",
    ],
    [
      "The sun is a",
      "planet",
      "moon",
      "star",
      "comet",
      "C",
      "Our nearest star",
    ],
    [
      "Which gas do humans breathe out?",
      "oxygen",
      "nitrogen",
      "carbon dioxide",
      "helium",
      "C",
      "Waste gas from respiration",
    ],
    [
      "An object that reflects light is",
      "transparent",
      "luminous",
      "opaque",
      "translucent",
      "B",
      "Wait — reflects = opaque; luminous = emits light. Best answer: opaque",
      "C",
      "Opaque objects reflect or absorb",
    ],
    ["Pure water has a pH of", "5", "7", "9", "11", "B", "Neutral pH = 7"],
    [
      "The force that pulls objects to Earth is",
      "friction",
      "gravity",
      "tension",
      "magnetism",
      "B",
      "Gravity = 9.8 m/s²",
    ],
    [
      "A lodestone is a natural",
      "conductor",
      "magnet",
      "insulator",
      "battery",
      "B",
      "Natural iron magnet",
    ],
    [
      "Plants get energy from",
      "wind",
      "sunlight",
      "soil",
      "water only",
      "B",
      "Photosynthesis uses sunlight",
    ],
    [
      "Which state of matter has no fixed shape or volume?",
      "solid",
      "liquid",
      "gas",
      "plasma",
      "C",
      "Gas takes container's shape/volume",
    ],
    [
      "Rust is formed when iron reacts with",
      "water only",
      "oxygen only",
      "water and oxygen",
      "acid",
      "C",
      "Oxidation process",
    ],
    [
      "The ear detects",
      "light",
      "sound",
      "smell",
      "taste",
      "B",
      "Sound waves cause eardrum vibration",
    ],
    [
      "Which is a mammal?",
      "eagle",
      "frog",
      "whale",
      "snake",
      "C",
      "Whales are warm-blooded mammals",
    ],
    [
      "Boiling is different from evaporation because",
      "it is slower",
      "it occurs only at a fixed temperature",
      "it needs no heat",
      "it happens below the boiling point",
      "B",
      "Boiling at specific temperature",
    ],
    [
      "Which is an example of a physical change?",
      "burning wood",
      "rusting iron",
      "melting ice",
      "cooking food",
      "C",
      "Melting is reversible/physical",
    ],
    [
      "The moon orbits the",
      "sun",
      "Earth",
      "Mars",
      "Jupiter",
      "B",
      "Natural satellite of Earth",
    ],
    [
      "Pitch of sound depends on",
      "amplitude",
      "frequency",
      "speed",
      "wavelength alone",
      "B",
      "High frequency = high pitch",
    ],
    [
      "Which material is a good conductor of electricity?",
      "wood",
      "rubber",
      "copper",
      "glass",
      "C",
      "Copper is a metal conductor",
    ],
    [
      "Food is digested in the",
      "heart",
      "lungs",
      "digestive system",
      "skeleton",
      "C",
      "Stomach, intestines etc.",
    ],
    [
      "A newton is a unit of",
      "mass",
      "weight/force",
      "energy",
      "power",
      "B",
      "F measured in Newtons",
    ],
    [
      "How many chambers does the human heart have?",
      "2",
      "3",
      "4",
      "5",
      "C",
      "Right and left atria and ventricles",
    ],
    [
      "Evaporation changes liquid to",
      "solid",
      "gas",
      "plasma",
      "crystal",
      "B",
      "Surface molecules escape",
    ],
    [
      "The chemical symbol for water is",
      "H₂O",
      "CO₂",
      "O₂",
      "H₂",
      "A",
      "2 hydrogen + 1 oxygen",
    ],
    [
      "Vertebrates have a",
      "shell",
      "backbone",
      "exoskeleton",
      "fin",
      "B",
      "Internal skeleton with spine",
    ],
    [
      "Which is a renewable source of energy?",
      "coal",
      "petroleum",
      "solar",
      "natural gas",
      "C",
      "Sun energy is inexhaustible",
    ],
    [
      "The tongue detects",
      "smell",
      "sound",
      "taste",
      "sight",
      "C",
      "Taste buds on tongue",
    ],
    [
      "Friction always acts in the",
      "same direction as motion",
      "opposite direction to motion",
      "perpendicular to motion",
      "vertical direction",
      "B",
      "Opposing force",
    ],
    [
      "DNA carries",
      "electrical signals",
      "genetic information",
      "energy",
      "water",
      "B",
      "Blueprint for living organisms",
    ],
    [
      "The liver is part of which system?",
      "respiratory",
      "digestive",
      "nervous",
      "circulatory",
      "B",
      "Produces bile; filters blood",
    ],
  ],
  "Primary Mathematics": [
    ["What is 7 × 8?", "54", "56", "64", "72", "B", "7×8=56"],
    ["Halve of 48 is", "12", "24", "36", "48", "B", "48÷2=24"],
    ["What comes after 99?", "90", "98", "100", "101", "C", "99+1=100"],
    ["9 + 7 = ?", "15", "16", "17", "18", "B", "9+7=16"],
    [
      "Which is the largest?",
      "347",
      "374",
      "437",
      "473",
      "D",
      "473 > 437 > 374 > 347",
    ],
    ["How many sides does a hexagon have?", "4", "5", "6", "7", "C", "Hex = 6"],
    [
      "2/4 simplified is",
      "1/2",
      "1/3",
      "2/3",
      "3/4",
      "A",
      "Divide top and bottom by 2",
    ],
    ["What is 1/2 of 30?", "10", "12", "15", "20", "C", "30÷2=15"],
    [
      "How many minutes in an hour?",
      "30",
      "45",
      "60",
      "100",
      "C",
      "60 minutes",
    ],
    ["Roman numeral for 10 is", "I", "V", "X", "L", "C", "X = 10"],
    [
      "The shape with 3 sides is a",
      "square",
      "rectangle",
      "triangle",
      "circle",
      "C",
      "Tri = 3",
    ],
    ["25 × 4 = ?", "75", "90", "100", "110", "C", "25×4=100"],
    ["456 - 123 = ?", "323", "333", "343", "353", "B", "456-123=333"],
    [
      "Which is an even number?",
      "13",
      "17",
      "18",
      "21",
      "C",
      "18 divisible by 2",
    ],
    ["12 ÷ 4 = ?", "2", "3", "4", "5", "B", "12÷4=3"],
    ["How many days in a week?", "5", "6", "7", "8", "C", "Monday to Sunday"],
    ["What is 0.5 as a fraction?", "1/4", "1/2", "3/4", "1/3", "B", "0.5 = ½"],
    ["15 + 28 = ?", "33", "41", "43", "53", "C", "15+28=43"],
    ["Which number is a multiple of 5?", "11", "13", "15", "17", "C", "5×3=15"],
    [
      "The perimeter of a square with side 4cm is",
      "8cm",
      "12cm",
      "16cm",
      "20cm",
      "C",
      "4×4=16",
    ],
    ["How many tens in 150?", "1", "5", "10", "15", "D", "150 = 15 tens"],
    ["3² = ?", "6", "8", "9", "12", "C", "3×3=9"],
    [
      "Which fraction is biggest?",
      "1/4",
      "1/3",
      "1/2",
      "1/5",
      "C",
      "Bigger denominator = smaller fraction",
    ],
    ["500 + 250 = ?", "700", "750", "800", "850", "B", "500+250=750"],
    ["A dozen = ?", "10", "11", "12", "13", "C", "One dozen = 12"],
    ["What is 40% of 50?", "15", "20", "25", "30", "B", "40/100×50=20"],
    [
      "The digit in the tens place of 382 is",
      "3",
      "8",
      "2",
      "38",
      "B",
      "8 is in tens place",
    ],
    [
      "How many months in a year?",
      "10",
      "11",
      "12",
      "13",
      "C",
      "January to December",
    ],
    [
      "Which is a prime number?",
      "4",
      "6",
      "7",
      "9",
      "C",
      "7 divisible only by 1 and 7",
    ],
    [
      "Area of rectangle 5cm × 6cm?",
      "11cm²",
      "22cm²",
      "30cm²",
      "60cm²",
      "C",
      "5×6=30",
    ],
  ],
};

// ─── Seed function ────────────────────────────────────────────────────────────
async function seed() {
  await connect();

  console.log("\n🗑  Clearing existing tests...");
  await Test.deleteMany({});

  console.log("📚 Loading exams, terms and subjects from DB...\n");

  // Flatten ALL questions from every bank into one pool
  const allBankRows = Object.values(QUESTION_BANKS).flat();
  console.log("📊 Total questions in bank: " + allBankRows.length);

  const exams = await Exam.find({});
  const allQuestions = [];

  for (const exam of exams) {
    console.log("\n📘 Exam: " + exam.name);

    const terms = await Term.find({ exam: exam._id });
    if (terms.length === 0) {
      console.log("  ⚠  No terms found — skipping");
      continue;
    }

    for (const term of terms) {
      console.log("  📗 Term: " + term.name);

      const subjects = await Subject.find({ term: term._id });
      if (subjects.length === 0) {
        console.log("    ⚠  No subjects found — skipping");
        continue;
      }

      for (const subject of subjects) {
        console.log("    📄 Subject: " + subject.subjectName);

        // Take 30 questions cycling through the full pool
        const TARGET = 30;
        const questions = [];
        for (let i = 0; i < TARGET; i++) {
          const row = allBankRows[i % allBankRows.length];
          questions.push({
            exam: exam._id,
            term: term._id,
            subject: subject._id,
            question: row[0],
            options: { A: row[1], B: row[2], C: row[3], D: row[4] },
            answer: row[5],
            explanation: row[6] ?? "",
            marks: 1,
            order: i + 1,
            isActive: true,
          });
        }

        allQuestions.push(...questions);
        console.log("       ✅ " + questions.length + " questions queued");
      }
    }
  }

  console.log("\n📝 Inserting " + allQuestions.length + " total questions...");
  const inserted = await Test.insertMany(allQuestions, { ordered: false });
  console.log("   ✅ " + inserted.length + " questions inserted");

  console.log("\n🎉 Seeding complete!\n");

  const counts = await Test.aggregate([
    { $group: { _id: "$subject", count: { $sum: 1 } } },
    {
      $lookup: {
        from: "subjects",
        localField: "_id",
        foreignField: "_id",
        as: "subjectDoc",
      },
    },
    { $unwind: "$subjectDoc" },
    { $project: { name: "$subjectDoc.subjectName", count: 1, _id: 0 } },
    { $sort: { name: 1 } },
  ]);

  console.log("─── Questions per subject ──────────────────────────────");
  counts.forEach((c) => console.log("  " + c.name + ": " + c.count + " questions"));
  console.log("  TOTAL: " + allQuestions.length + " questions across " + counts.length + " subjects");
  console.log("─────────────────────────────────────────────────────\n");

  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err.message);
  mongoose.disconnect();
  process.exit(1);
});

